# Generated by Django 3.0.3 on 2020-04-28 17:20

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200428_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=feed.models.user_feed_image_path),
        ),
    ]
