# Generated by Django 3.0.3 on 2020-04-29 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20200428_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
