# Generated by Django 3.0.3 on 2020-05-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20200429_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'post'},
        ),
    ]
