# Generated by Django 3.0.3 on 2020-04-11 17:30

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_fisrt_name', models.CharField(max_length=255)),
                ('contact_last_name', models.CharField(max_length=255)),
                ('contact_phone', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('school_size', models.CharField(choices=[('small', 'less than 100 students'), ('medium', '101 to 500 students'), ('wide', '501 to 1000 students'), ('extra wide', '1001+ students')], max_length=255)),
                ('paid_until', models.DateField(null=True)),
                ('on_trial', models.BooleanField(null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customer.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
