# Generated by Django 3.0.3 on 2020-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='school.Course'),
        ),
    ]
